name: build-bundle
channels:
  - napari/label/bundle_tools_2
  - conda-forge
dependencies:
  - python
  - pip
  - constructor
  - conda-build
  - ruamel.yaml
  - conda-standalone
  - conda
  - conda-libmamba-solver
